#!/bin/bash

SSH_USERNAME="youruser"
SSH_HOST="yourhost"
SSH_KEY="./.deploy/id_deployer"

DEPLOY_PATH="/the/path/to/your/project/root"
DEPLOY_MODE="development"
DEPLOY_BRANCH="master"

# Process of this file
# 1. Push the current changes to the git repo
# 2. Log in via ssh to the remote server
# 3. Pull the changes from github
# 4. Start the build process

# -- PUSH CHANGES TO GITHUB --
git add .
git commit -m "[RELEASE] commit for deployment - IMPORTANT: this commit is auto-generated by the deploy script"
git push origin ${DEPLOY_BRANCH} --force

# -- LOG IN VIA SSH TO REMOTE --
ssh -i ${SSH_KEY} ${SSH_USERNAME}@${SSH_HOST} "

    cd ${DEPLOY_PATH};
    git reset --hard HEAD;
    git pull origin ${DEPLOY_BRANCH};
    yarn install;
    yarn build --mode=${DEPLOY_MODE}
";
